### PR TITLE
Prevent direct usage of addView in ContourLayout subclasses (resolves #70)

### LINKED ISSUE #70: Lint error when adding a view manually to a contour layout.
This would otherwise crash when casting the LayoutSpec
```kotlin
  private inline fun View.spec(): LayoutSpec {
    if (parent !== this@ContourLayout) {
      throw IllegalArgumentException("Referencing view outside of ViewGroup.")
    }
    return layoutParams as LayoutSpec
  }
```

### PR DESCRIPTION
**Pull request by carranca**
addview

### CODE REVIEW

File: contour/src/main/kotlin/com/squareup/contour/ContourLayout.kt [hunk 1]
```diff
@@ -387,7 +389,8 @@ open class ContourLayout(
       it.view = this
     }
     if (addToViewGroup && parent == null) {
-      viewGroup.addView(this)
+      // Cast to ViewGroup to skirt our own public deprecation
+      (viewGroup as ViewGroup).addView(this)
```
Comment (saket) [inline contour/src/main/kotlin/com/squareup/contour/ContourLayout.kt:393]: This makes me realize that we will also need to throw an error in `addView()` in case a `ContourLayout` is passed around in a generic way and `addView()` gets called on it.

Comment (carranca) [reply contour/src/main/kotlin/com/squareup/contour/ContourLayout.kt:357]: At that point are we being over-zealous? And how would one distinguish external (i.e. `myContourLayoutInDisguise.addView`) vs internal (i.e. `this.addView`) calls?

I think there's only so much we can do to remove this footgun, but I'm open to ideas!

Comment (saket) [reply contour/src/main/kotlin/com/squareup/contour/ContourLayout.kt:357]: Hmmmm what do you think of adding a private function that delegates to `super.addView()`?

```kotlin
private fun addViewInternal(child: View) {
  super.addView(child)
}

@Deprecated(level = ERROR)
override fun addView(child: View?) {
  super.addView(child)
}

fun <T : View> T.layoutBy(...): T {
  ...
  if (addToViewGroup && parent == null) {
    viewGroup.addViewInternal(this)
  }
  return this
}
```

The error message thrown if a view is added using `addView()` results isn't very obvious and I think we could help users avoid it this way.

Comment (carranca) [reply contour/src/main/kotlin/com/squareup/contour/ContourLayout.kt:357]: We can add the throwing for `addView`, but I wouldn't want to do it for the overloads, as they get called directly by `ViewGroup`'s implementation

Comment (saket) [reply contour/src/main/kotlin/com/squareup/contour/ContourLayout.kt]: What do you think of throwing an error in the last `addView()` call if the layoutParam != LayoutSpec?

Comment (carranca) [reply contour/src/main/kotlin/com/squareup/contour/ContourLayout.kt]: That might just do it, and then we don't really need `addViewInternal`

Comment (carranca) [reply contour/src/main/kotlin/com/squareup/contour/ContourLayout.kt]: LMK how this looks

**Comment by carranca** [comment]
@saket 👍 👇 plz
